### ISSUE TITLE
ICX6430 connect hangs

### ISSUE THREAD

**Issue by danse-entropy** [DavidJohnGee/clicrud#1]
On a ICX6430 (and FLS-48G) python hangs during the transport command while trying to run the command transport = device(...). I cannot enter any command after that line until i Control-C that task.

clicrud-paramiko.log shows that the script successfully logins in.

> DEBUG:paramiko.transport:starting thread (client mode): 0x2d98390L
> DEBUG:paramiko.transport:Local version/idstring: SSH-2.0-paramiko_1.16.0
> DEBUG:paramiko.transport:Remote version/idstring: SSH-2.0-RomSShell_4.61
> INFO:paramiko.transport:Connected (version 2.0, client RomSShell_4.61)
> DEBUG:paramiko.transport:kex algos:[u'diffie-hellman-group1-sha1'] server key:[u'ssh-dss'] client encrypt:[u'aes256-cbc', u'aes192-cbc', u'aes128-cbc', u'3des-cbc'] server encrypt:[u'aes256-cbc', u'aes192-cbc', u'aes128-cbc', u'3des-cbc'] client mac:[u'hmac-sha1'] server mac:[u'hmac-sha1'] client compress:[u'none'] server compress:[u'none'] client lang:[u''] server lang:[u''] kex follows?False
> DEBUG:paramiko.transport:Kex agreed: diffie-hellman-group1-sha1
> DEBUG:paramiko.transport:Cipher agreed: aes128-cbc
> DEBUG:paramiko.transport:MAC agreed: hmac-sha1
> DEBUG:paramiko.transport:Compression agreed: none
> DEBUG:paramiko.transport:kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
> DEBUG:paramiko.transport:Switch to new keys ...
> DEBUG:paramiko.transport:Adding ssh-dss host key for 10.x.x.x: 50ad3b873cbe42d39624e60d6813cf73
> DEBUG:paramiko.transport:userauth is OK
> INFO:paramiko.transport:Auth banner: 
> INFO:paramiko.transport:Authentication (password) successful!
> DEBUG:paramiko.transport:[chan 0] Max packet in: 32768 bytes
> DEBUG:paramiko.transport:[chan 0] Max packet out: 4096 bytes
> DEBUG:paramiko.transport:Secsh channel 0 opened.
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok
> DEBUG:paramiko.transport:[chan 0] Sesch channel 0 request ok

It doesn't matter if i connect via SSH or Telnet.

A test run on a VDX 6740 worked fine.

**Comment by DavidJohnGee** [comment]
What software version on the ICX6430 are you testing on? I'll get access to some gear and replicate.

Also, sorry for the delay.

**Comment by danse-entropy** [comment]
```
SSH@sw1#show version
  Copyright (c) 1996-2015 Brocade Communications Systems, Inc. All rights reserved.
    UNIT 1: compiled on Nov  3 2015 at 21:43:36 labeled as ICX64S08030d
                (8486536 bytes) from Primary ICX64S08030d.bin
        SW: Version 08.0.30dT311
  Boot-Monitor Image size = 786944, Version:10.1.05T310 (kxz10105)
  HW: Stackable ICX6450-48
==========================================================================
UNIT 1: SL 1: ICX6450-48 48-port Management Module
         Serial  #: <serial>
         License: BASE_SOFT_PACKAGE   (LID: <lid>)
         P-ENGINE  0: type DEF0, rev 01
         P-ENGINE  1: type DEF0, rev 01
==========================================================================
UNIT 1: SL 2: ICX6450-SFP-Plus 4port 40G Module
==========================================================================
  800 MHz ARM processor ARMv5TE, 400 MHz bus
65536 KB flash memory
  512 MB DRAM
STACKID 1  system uptime is 13 day(s) 17 hour(s) 43 minute(s) 14 second(s)
The system started at 14:50:50 GMT+01 Wed Jul 06 2016

 The system : started=cold start
```

**Comment by DavidJohnGee** [comment]
Code just pushed to Pypi with update 0.2.14. This resolved hanging issues across the board hopefully for you too. I have tested MLX, ICX, VDX with Telnet and SSH. So far so good. Please upgrade your version of CLICRUD and report back the results!

**Comment by DavidJohnGee** [comment]
Code pushed to 0.2.15. This includes the fixing of bugs incurred from a previous effort to simplify CLICRUD. Please update to the latest and let me know the news! I have tested on ICX, MLX, VDX and with Telnet and SSH. Tests prove so far so good. If there are any issues, it could be sub-platform dependent and we will need to investigate further.
