### ISSUE TITLE
class ssh(object): - ssh 'hangs'

### ISSUE THREAD

**Issue by jpvrenen** [DavidJohnGee/clicrud#2]
After a reinstall and upgrade to version 0.2.13 from version 0.1.4 we could no longer send commands to the brocade. (ssh hangs)

Seems like the following additions is causing issues:
509       self.output = self.blocking_recv()
510       self.output = self.blocking_recv() (this second statement seems to work fine with NOS)
Commenting out 510 does work, however the 'show version' command is causing paging so to fix this we could add:
      if _NOS_present:
          self.client_conn.send("terminal length 0\n")
      else:
          _self.client_conn.send("q\n")
          self.output = self.blocking_recv()_
          self.client_conn.send("skip\n")

Then this module works again however it breaks NOS.

We have replaced everything below line 503 with the code of version 0.1.4
            if "#" in self.output:
                self.client_conn.send("\n")
                self.output = self.blocking_recv()
                self._hostname = self.output.translate(None, '\r\n')
                self.client_conn.send("skip\n")
                self.output = self.blocking_recv()

Thanks, Jeroen

**Comment by DavidJohnGee** [comment]
I'll fix this.

There were some changes to make CLICRUD simpler and of course, it broke stuff.

Can you be specific please about what equipment and software versions you are using?

Thanks,

**Comment by jpvrenen** [comment]
Hi,
We are using a MLX router (MLXe-4), software: Version 5.6.0T165

Thanks

**Comment by DavidJohnGee** [comment]
Ok, please try again. Code is now at 0.2.14 and I've tested against MLX, ICX & VDX with both SSH and Telnet. Some silly issues resolved (hopefully). Please let me know how you go on when you do a pip install clicrud --upgrade.

Thanks

**Comment by DavidJohnGee** [comment]
Code has been pushed to 0.2.15, which includes a minor NOS pagination fix. Please update and let me know the news!

**Comment by jpvrenen** [comment]
Hi David,

Upgrade done to latest 0.2.15, it is working!

Thank you!

Jeroen

---

Van: David Gee notifications@github.com
Verzonden: donderdag 4 augustus 2016 12:28
Aan: DavidJohnGee/clicrud
CC: jpvrenen; Author
Onderwerp: Re: [DavidJohnGee/clicrud] class ssh(object): - ssh 'hangs' (#2)

Code has been pushed to 0.2.15, which includes a minor NOS pagination fix. Please update and let me know the news!

##
