### ISSUE TITLE
ICX6610-48P Password Prompt

### ISSUE THREAD

**Issue by nmusser** [DavidJohnGee/clicrud#9]
Connecting to a ICX6610-48P running 07.4.00dT7f1 fails. It appears that the password prompt is caught by and sent from the if statement in clicrud/clicrud/device/generic/ver/base/__init__.py on line 137, but immediately after that if statement _detect is set back to True and clicrud is caught back trying to read for a password prompt and fails because the device is now at the device prompt.

**Comment by DavidJohnGee** [comment]
Thanks for raising this. I'll sort this in the next couple of days. 

The code you are referring to is a false positive on detecting a CLI race problem. I'll mend this and respond on completion.

**Comment by nmusser** [comment]
Any progress made on this?

**Comment by DavidJohnGee** [comment]
I can't recreate what you're seeing, but I did find a 'password' flow issue. I'm running Telnet on version: 07.4.00jT7f3 on an ICX6610-48 and mine works. Next job if this push doesn't work is for me to run your software version. I've pushed CLICRUD 0.3.03. Please upgrade and report back. You can do this using pip.

**Comment by nmusser** [comment]
I tested and your changes did work. Thanks!
